apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: did-solution-backend
  namespace: lgcns-tenant
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: did-solution-backend
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
