apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  selector:
    matchLabels:
      app: redis-slave
  template:
    metadata:
      name: redis-slave
      labels:
        app: redis-slave
    spec:
      containers:
      - name: redis
        image: redis:7.0.2-bullseye
        command:
          - redis-server
          - /etc/redis/redis.conf
        envFrom:
          - configMapRef:
              name: redis-slave-env
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 0.5
        volumeMounts:
        - mountPath: /etc/redis
          name: config
        - mountPath: /var/redis
          name: data
      volumes:
        - name: config
          configMap:
            name: redis-slave-config
            items:
            - key: redis-conf
              path: redis.conf  
        - name: data
          emptyDir: {}
