apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-slave-env
data:
  MASTER: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-slave-config
data:
  redis-conf: |
    replicaof redis 6379
    appendonly no
    save ""