spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  profiles:
    active: default
server:
  port: 9090
  
# We're including this here to allow for running JUnit module tests in the IDE. 
# Ideally we could configure JUnit to use src/test/resources/application.yml the way ./gradlew integrationTest does, but this fix works for now.
local:
  server:
    port: 9090
    address: http://localhost

payer-service-client:
  feign:
    hystrix:
      enabled: false

https:
  protocols: TLSv1

---
spring:
  profiles: default

logging:
  level:
    com.lgcns.vportal: debug
feign:
  httpclient:
    disableSslValidation: true
  client:
    config:
      default:
        connectTimeout: 10_000
        readTimeout: 30_000
        loggerLevel: FULL
  retryer:
    period: 1000
    maxPeriod: 1000
    maxAttempts: 0

vportal:
  visit:
    host: https://intf-mock.vportaldev.koreabuild.com/mockserver/visit
    port:
    uri:
      approved: /v1/intf/approve

apim:
  host: https://intf-mock.vportaldev.koreabuild.com/mockserver/apim
  port:
  uri:
    check: /v1/valid

idp:
  sifsystemid: defaultsif12345

env: deafult
---
spring:
  profiles: feature

logging:
  level:
    com.lgcns.vportal: debug
feign:
  httpclient:
    disableSslValidation: true
  client:
    config:
      default:
        connectTimeout: 10_000
        readTimeout: 30_000
        loggerLevel: FULL
  retryer:
    period: 1000
    maxPeriod: 1000
    maxAttempts: 0

vportal:
  visit:
    host: https://127.0.0.1
    port: 1081
    uri:
      approved: /v1/approved

apim:
  host: https://127.0.0.1
  port: 1082
  uri:
    check: /v1/valid

idp:
  sifsystemid: featuresif12345

env: feature
---
spring:
  profiles: dev

logging:
  level:
    com.lgcns.vportal: debug

feign:
  httpclient:
    disableSslValidation: true
  client:
    config:
      default:
        connectTimeout: 10_000
        readTimeout: 30_000
        loggerLevel: FULL
  retryer:
    period: 1000
    maxPeriod: 1000
    maxAttempts: 0

vportal:
  visit:
    host: https://visit.vportaldev.koreabuild.com
    port:
    uri:
      approved: /v1/intf/approve

apim:
  host: https://127.0.0.1
  port: 1082
  uri:
    check: /v1/valid

idp:
  sifsystemid: 0dk403jsdf9302i304dkf0d

env: dev
---
spring:
  profiles: stage

logging:
  level:
    com.lgcns.vportal: debug
feign:
  httpclient:
    disableSslValidation: true
  client:
    config:
      default:
        connectTimeout: 10_000
        readTimeout: 30_000
        loggerLevel: FULL
  retryer:
    period: 1000
    maxPeriod: 1000
    maxAttempts: 0

vportal:
  visit:
    host: https://visit.vportalstg.koreabuild.com
    port:
    uri:
      approved: /v1/intf/approve

apim:
  host: https://127.0.0.1
  port: 1082
  uri:
    check: /v1/valid

idp:
  sifsystemid: 0dk403jsdf9302i304dkf0d

env: stage
---
spring:
  profiles: prod

logging:
  level:
    com.lgcns.vportal: debug
feign:
  httpclient:
    disableSslValidation: true
  client:
    config:
      default:
        connectTimeout: 10_000
        readTimeout: 30_000
        loggerLevel: FULL
  retryer:
    period: 1000
    maxPeriod: 1000
    maxAttempts: 0

vportal:
  visit:
    host: https://visit.vportalprd.koreabuild.com
    port:
    uri:
      approved: /v1/intf/approve

apim:
  host: https://127.0.0.1
  port: 1082
  uri:
    check: /v1/valid

idp:
  sifsystemid: 0dk403jsdf9302i304dkf0d

env: prod
---
spring:
  profiles: testing

logging:
  level:
    com.lgcns.vportal: debug
feign:
  httpclient:
    disableSslValidation: true
  client:
    config:
      default:
        connectTimeout: 10_000
        readTimeout: 30_000
        loggerLevel: FULL
  retryer:
    period: 1000
    maxPeriod: 1000
    maxAttempts: 0

vportal:
  visit:
    host: https://127.0.0.1
    port: 1081
    uri:
      approved: /v1/intf/approve

apim:
  host: https://127.0.0.1
  port: 1082
  uri:
    check: /v1/valid

idp:
  sifsystemid: testsif12345
  
env: testing
