spring:
  application:
    name: did-service-backend
    version: 0.1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: ${DID_SERVER_PORT:9090}
  address: 0.0.0.0
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  level:
    did: ${DID_LOG_LEVEL:debug}
cors:
  patterns: ${DID_CORS_PATTERNS:"*"}
