spring:
  application:
    name: did-solution-backend
    version: 0.1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DID_DATABASE_URL:jdbc:postgresql://34.64.237.85:5432/solution}
    username: ${DID_DATABASE_USER:solution}
    password: ${DID_DATABASE_PASS:0sRyPSoK7p7i6Ygk1dewaPkRoy3K5Z/+}
  jpa:
    hibernate:
      ddl-auto: ${DID_DATABASE_DDL_AUTO:none}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        default_schema: DID_SOLUTION
        show_sql: true
        format_sql: true
        user_sql_comments: true
    open-in-view: false
  redis:
    host: ${DID_REDIS_HOST:127.0.0.1}
    port: ${DID_REDIS_PORT:6379}
    database: ${DID_REDIS_DB_INDEX:0}
    jedis:
      pool:
        max-active: ${DID_REDIS_POOL_MAX_ACTIVE:8}
        max-idle: ${DID_REDIS_POOL_MAX_IDLE:8}
        min-idle: ${DID_REDIS_POOL_MIN_IDLE:0}
server:
  port: ${DID_SERVER_PORT:9090}
  address: 0.0.0.0
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  level:
    did: ${DID_LOG_LEVEL:info}
management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: always
cors:
  patterns: ${DID_CORS_PATTERNS:*}
aries:
  admin:
    url: ${DID_ARIES_ADMIN_URL:http://acapy-multitenancy-admin}
    token: ${DID_ARIES_ADMIN_TOKEN:pbFVy2NKFWcEiMQv29+SEllihK/1TCWyyGx6OlBqiOo4TVjDzKyBAGhraz6NWiVz}



