spring:
  application:
    name: did-solution-backend
    version: 0.1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/solution
    username: postgres
    password: mysecretpasword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        user_sql_comments: true
    open-in-view: false

server:
  port: ${DID_SERVER_PORT:9090}
  address: 0.0.0.0
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  level:
    did: ${DID_LOG_LEVEL:debug}
cors:
  patterns: ${DID_CORS_PATTERNS:"*"}



