apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-solution-backend
  namespace: common-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: solution-backend
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
