apiVersion: v1
kind: Service
metadata:
  name: service-did-solution-backend
  namespace: common-system
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: did-solution-backend
