version: "3"
services:
  solution-db:
    image: postgres:13-buster
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=solution
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpasword
      - TZ=UTC
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  redis-db:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    ports:
      - 6379:6379
