-- auto-generated definition
create schema DID_SOLUTION;

comment on schema DID_SOLUTION is 'DID SOLUTION';

alter schema DID_SOLUTION owner to postgres;

grant create, usage on schema DID_SOLUTION to DID_SOLUTION;

create table DID_SOLUTION.account
(
    id                  bigint generated by default as identity (maxvalue 2147483647)
        primary key,
    account_id          varchar(255) not null,
    pswd_hash_val       varchar(255),
    pswd_falr_tmcnt     integer      not null,
    flnm                varchar(255) not null,
    cpno                varchar(31),
    email               varchar(255),
    account_status      varchar(15)  not null,
    account_type        varchar(15),
    auth_ip             varchar(255),
    last_login_dttm     timestamp,
    last_pswd_chng_dttm timestamp,
    login_sesn_id       varchar(255),
    frst_rgsr_id        varchar(255) not null,
    frst_reg_prog_id    varchar(255) not null,
    frst_reg_dttm       timestamp    not null,
    last_edtr_id        varchar(255) not null,
    last_chng_prog_id   varchar(255) not null,
    last_chng_dttm      timestamp
);

comment on table DID_SOLUTION.account is 'Admin 관리자 계정';

comment on column DID_SOLUTION.account.id is '계정일련번호';

comment on column DID_SOLUTION.account.account_id is '계정ID';

comment on column DID_SOLUTION.account.pswd_hash_val is '비밀번호 HASH';
comment on column DID_SOLUTION.account.pswd_falr_tmcnt is '비밀번호 실패 횟수';

comment on column DID_SOLUTION.account.flnm is '이름';

comment on column DID_SOLUTION.account.cpno is '휴대전화번호';

comment on column DID_SOLUTION.account.email is '이메일';

comment on column DID_SOLUTION.account.account_status is '계정상태';
comment on column DID_SOLUTION.account.account_type is '계정종류 (ADMIN/GENERAL)';

comment on column DID_SOLUTION.account.auth_ip is '접속가능IP';

comment on column DID_SOLUTION.account.last_login_dttm is '최종 접속일';

comment on column DID_SOLUTION.account.last_pswd_chng_dttm is '패스워드변경일';

comment on column DID_SOLUTION.account.login_sesn_id is '로그인세션ID';


comment on column DID_SOLUTION.account.frst_reg_prog_id is '최초등록프로그램ID';

comment on column DID_SOLUTION.account.frst_rgsr_id is '최초등록자ID';

comment on column DID_SOLUTION.account.last_chng_prog_id is '최종변경프로그램ID';

comment on column DID_SOLUTION.account.last_chng_dttm is '최종변경일시';

comment on column DID_SOLUTION.account.last_edtr_id is '최종변경자ID';

alter table DID_SOLUTION.account
    owner to DID_SOLUTION.solution;

-- auto-generated definition
create sequence account_id_seq
    maxvalue 2147483647;

alter sequence account_id_seq owner to solution;

alter sequence account_id_seq owned by account.id;


create unique index DID_SOLUTION.account_account_id_uindex
    on DID_SOLUTION.account (account_id);




create table DID_SOLUTION.tenant
(
    id                    bigint             bigint generated by default as identity (maxvalue 2147483647)
        primary key,
    tenant_id             varchar(20)           not null,
    tenant_type           varchar(16)           not null,
    tenant_name           varchar(200)          not null,
    tenant_did            varchar(100),
    tenant_status         varchar(10)           not null,
    tenant_home_url       varchar(1000),
    tenant_invitation_url varchar(1000),
    tenant_logo_path      varchar(3000),
    tenant_addr           varchar(1000),
    trust_tenant          boolean default false not null,
    frst_rgsr_id          varchar(100)          not null,
    frst_reg_prog_id      varchar(200)          not null,
    frst_reg_dttm         timestamp             not null,
    last_edtr_id          varchar(100),
    last_chng_prog_id     varchar(200),
    last_chng_dttm        timestamp
);

comment on table DID_SOLUTION.tenant is '참여기관';

comment on column DID_SOLUTION.tenant.tenant_id is '참여기관일련번호';

comment on column DID_SOLUTION.tenant.tenant_type is '참여기관 종류 (ISSUER/VERIFIER/ALL)';

comment on column DID_SOLUTION.tenant.tenant_name is '참여기관명';

comment on column DID_SOLUTION.tenant.tenant_did is '참여기관DID';

comment on column DID_SOLUTION.tenant.tenant_status is '참여기관상태';

comment on column DID_SOLUTION.tenant.tenant_home_url is '참여기관홈페이지';

comment on column DID_SOLUTION.tenant.tenant_invitation_url is '참여기관 Invitation url';

comment on column DID_SOLUTION.tenant.tenant_logo_path is '발급기관 목록에 보여지는 로고이미지 파일의 저장 경로';

comment on column DID_SOLUTION.tenant.tenant_addr is '참여기관주소';

comment on column DID_SOLUTION.tenant.trust_tenant is '공개신뢰기관여부';

comment on column DID_SOLUTION.tenant.frst_rgsr_id is '최초등록자ID';

comment on column DID_SOLUTION.tenant.frst_reg_prog_id is '최초등록프로그램ID';

comment on column DID_SOLUTION.tenant.frst_reg_dttm is '최초등록일시';

comment on column DID_SOLUTION.tenant.last_edtr_id is '최종변경자ID';

comment on column DID_SOLUTION.tenant.last_chng_prog_id is '최종변경프로그램ID';

comment on column DID_SOLUTION.tenant.last_chng_dttm is '최종변경일시';

alter table DID_SOLUTION.tenant
    owner to solution;

create unique index tenant_tenant_id_uindex
    on DID_SOLUTION.tenant (tenant_id);

-- auto-generated definition
create sequence tenant_id_seq
    maxvalue 2147483647;

alter sequence tenant_id_seq owner to solution;

alter sequence tenant_id_seq owned by tenant.id;


INSERT INTO DID_SOLUTION.tenant (id, tenant_id, tenant_type, tenant_name, tenant_did, tenant_status, tenant_home_url, tenant_invitation_url, tenant_logo_path, tenant_addr, trust_tenant, frst_rgsr_id, frst_reg_prog_id, frst_reg_dttm, last_edtr_id, last_chng_prog_id, last_chng_dttm) VALUES (1, 'ISStjalskdjxc', 'ISSUER', 'LG CNS', 'RTHAnR3aKM5iSNmHnr4am4', 'ACTIVATE', null, 'https://devacapyinbound.duckdns.org?c_i=eyJAdHlwZSI6ICJkaWQ6c292OkJ6Q2JzTlloTXJqSGlxWkRUVUFTSGc7c3BlYy9jb25uZWN0aW9ucy8xLjAvaW52aXRhdGlvbiIsICJAaWQiOiAiZDU1ZGFiOTYtNjk4Yi00M2U0LWI3ZmItNTUzMTg1ZjcwOGZmIiwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwczovL2RldmFjYXB5aW5ib3VuZC5kdWNrZG5zLm9yZyIsICJpbWFnZVVybCI6ICJodHRwczovL3JvYm9oYXNoLm9yZy9MR0NOUyIsICJsYWJlbCI6ICJMR0NOUyIsICJyZWNpcGllbnRLZXlzIjogWyJGc0VEbjRlZmdLTnBlRXFRWXlpZmNLRlM3NkxTWHVXbkhuWjR1ZGRLeVRvdiJdfQ==', null, null, true, 'test', 'test', '2022-01-01 11:11:11.000000', 'test', 'test', '2022-01-01 11:11:11.000000');




create table did_solution.faq
(
    id                bigint generated by default as identity (maxvalue 2147483647)
        primary key,
    faq_class         varchar(16)                                      not null,
    faq_title         varchar(256)                                     not null,
    faq_display_range varchar(3)                                       not null,
    faq_content       varchar(2048)                                    not null,
    faq_status        varchar(16) default 'WRITING'::character varying not null,
    frst_rgsr_id      varchar(100)                                     not null,
    frst_reg_prog_id  varchar(200)                                     not null,
    frst_reg_dttm     timestamp                                        not null,
    last_edtr_id      varchar(100),
    last_chng_prog_id varchar(200),
    last_chng_dttm    timestamp
);

comment on table did_solution.faq is 'FAQ';

comment on column did_solution.faq.id is 'FAQ 일련번호';

comment on column did_solution.faq.faq_class is 'FAQ분류 (TENENT: 참여기관 PRICING: 과금정책 SYSTEM: 시스템장애 ETC:기타)';

comment on column did_solution.faq.faq_title is 'FAQ제목';

comment on column did_solution.faq.faq_display_range is '노출범위: I,V,H';

comment on column did_solution.faq.faq_content is 'FAQ내용';

comment on column did_solution.faq.faq_status is '노출상태(WRITING:작성중, PUBLISH:발행, EXPIRATIO:만료)';

comment on column did_solution.faq.frst_rgsr_id is '최초등록자ID';

comment on column did_solution.faq.frst_reg_prog_id is '최초등록프로그램ID';

comment on column did_solution.faq.frst_reg_dttm is '최초등록일시';

comment on column did_solution.faq.last_edtr_id is '최종변경자ID';

comment on column did_solution.faq.last_chng_prog_id is '최종변경프로그램ID';

comment on column did_solution.faq.last_chng_dttm is '최종변경일시';

alter table did_solution.faq
    owner to solution;

-- auto-generated definition
create sequence faq_id_seq
    maxvalue 2147483647;

alter sequence faq_id_seq owner to solution;

alter sequence faq_id_seq owned by DID_SOLUTION.faq.id;



CREATE TABLE DID_SOLUTION.NOTICE (
     id                  bigint generated by default as identity (maxvalue 2147483647)
         primary key,
     NOTICE_LEVEL varchar(15)  NOT NULL ,
     NOTICE_TITLE varchar(200)  NOT NULL ,
     NOTICE_RANGE varchar(15)  NOT NULL ,
     NOTICE_CONTENT varchar(8000)  NOT NULL ,
     NOTICE_STATUS varchar(15)  DEFAULT NULL ,
     NOTICE_START_DATE timestamp  DEFAULT NULL ,
     NOTICE_END_DATE timestamp  DEFAULT NULL ,
     FRST_RGSR_ID varchar(100)  DEFAULT NULL ,
     FRST_REG_PROG_ID varchar(200)  DEFAULT NULL ,
     FRST_REG_DTTM timestamp NULL DEFAULT NULL ,
     LAST_EDTR_ID varchar(100)  DEFAULT NULL ,
     LAST_CHNG_PROG_ID varchar(200)  DEFAULT NULL ,
     LAST_CHNG_DTTM timestamp NULL DEFAULT NULL

);

comment on table DID_SOLUTION.NOTICE is '공지사항';

comment on column DID_SOLUTION.NOTICE.id is '공지사항 일련번호';
COMMENT on column did_solution.notice.NOTICE_LEVEL is '공지사항구분코드(CRITICAL: 중요공지, GENERAL: 일반공지)';
COMMENT on column did_solution.notice.NOTICE_TITLE is '공지사항제목';
COMMENT on column did_solution.notice.NOTICE_RANGE is '노출범위 IVH';
COMMENT on column did_solution.notice.NOTICE_CONTENT is '공지내용';
COMMENT on column did_solution.notice.NOTICE_RANGE is  '노출상태(WRITING:작성중, PUBLISH:발행, EXPIRATION:만료)'
COMMENT on column did_solution.notice.NOTICE_START_DATE is  '공지사항시작일자';
COMMENT on column did_solution.notice.NOTICE_END_DATE is  '공지사항종료일자';

comment on column did_solution.notice.frst_rgsr_id is '최초등록자ID';

comment on column did_solution.notice.frst_reg_prog_id is '최초등록프로그램ID';

comment on column did_solution.notice.frst_reg_dttm is '최초등록일시';

comment on column did_solution.notice.last_edtr_id is '최종변경자ID';

comment on column did_solution.notice.last_chng_prog_id is '최종변경프로그램ID';

comment on column did_solution.notice.last_chng_dttm is '최종변경일시';


-- auto-generated definition
create sequence notice_id_seq
    maxvalue 2147483647;

alter sequence notice_id_seq owner to solution;

alter sequence notice_id_seq owned by notice.id;




///////////////

-- auto-generated definition
create table credential
(
    id                       bigint generated by default as identity (maxvalue 2147483647)
        primary key,
    credential_id            varchar(200)      not null,
    tenant_id                bigint            not null
        constraint credential_tenant_id_fk
            references tenant,
    schema_id                bigint            not null,
    credential_name          varchar(200)      not null,
    credential_definition_id varchar(200)      not null,
    trust_credential_yn      boolean           not null,
    credential_type          varchar(20)       not null,

    Credential_STATUS VARCHAR(20) ,
    revocation_registry_size integer default 0 not null,
    description              varchar(200),
    user_auth_page_url       varchar(500)      not null,
    exp_dt_set_yn            varchar(1)        not null,
    validity_days            integer,
    background_img           bytea,
    logo_img                 bytea,
    temp_item_mapping        varchar(3000)     not null,
    frst_rgsr_id             varchar(100)      not null,
    frst_reg_prog_id         varchar(200)      not null,
    frst_reg_dttm            timestamp         not null,
    last_edtr_id             varchar(100)      not null,
    last_chng_prog_id        varchar(200)      not null,
    last_chng_dttm           timestamp         not null

);

comment on table credential is '증명서';

comment on column credential.id is '증명서 일련번호';

comment on column credential.credential_id is '증명서 ID';

comment on column credential.credential_name is '증명서명(사용자화면노출)';

comment on column credential.credential_definition_id is 'CredentialDefinitionId';

comment on column credential.trust_credential_yn is 'trust 인증서 여부';

comment on column credential.credential_type is '스키마유형(EMPLOYEEID)';

COMMENT ON COLUMN DID_SOLUTION.Credential.Credential_STATUS IS '증명서 상태(심사중, 심사완료)';

comment on column credential.revocation_registry_size is '발급규모';

comment on column credential.description is '증명서설명';

comment on column credential.user_auth_page_url is '사용자인증페이지URL';

comment on column credential.exp_dt_set_yn is '유효기간설정여부';

comment on column credential.validity_days is '유효기간일수';

comment on column credential.background_img is '배경이미지';

comment on column credential.logo_img is '로고이미지';

comment on column credential.temp_item_mapping is '속성매핑
변수항목-크리덴셜속성 연결정보
;를 구분자로 변수항목과 속성을 번갈아가며 기술.
예)3;cla.compname;CompanyNm;cla.empname;EmpNm;cla.empno;EmpNo';

comment on column credential.frst_rgsr_id is '최초등록자ID';

comment on column credential.frst_reg_prog_id is '최초등록프로그램ID';

comment on column credential.frst_reg_dttm is '최초등록일시';

comment on column credential.last_edtr_id is '최종변경자ID';

comment on column credential.last_chng_prog_id is '최종변경프로그램ID';

comment on column credential.last_chng_dttm is '최종변경일시';

alter table credential
    owner to solution;

create index credential_credential_id_index
    on credential (credential_id);



