-- ACCOUNT DEFINITION

-- DROP TABLE

-- DROP TABLE ACCOUNT;

CREATE TABLE ACCOUNT (
	ID INT8 NOT NULL COMMENT '계정일련번호',
	ACC_ID VARCHAR(255) NOT null COMMENT '계정ID',
	FLNM VARCHAR(255) NOT null COMMENT '이름',
	PSWD_HASH_VAL VARCHAR(255) COMMENT '비밀번호 HASH',
	PSWD_FALR_TMCNT INT4 NOT null COMMENT '비밀번호 실패 횟수',
	ACC_STAT VARCHAR(255) NOT null COMMENT '계정상태',
	ACC_TYPE VARCHAR(255) NOT null COMMENT '계정권한',
	AUTH_IP VARCHAR(255) COMMENT '접속가능IP',
	CPNO VARCHAR(255),
	EMAIL VARCHAR(255),
	LAST_LOGIN_DTTM TIMESTAMP,
	LAST_PSWD_CHNG_DTTM TIMESTAMP,
	LOGIN_SESN_ID VARCHAR(255),
	FRST_RGSR_ID VARCHAR(255) NOT NULL,
	FRST_REG_PROG_ID VARCHAR(255) NOT NULL,
	FRST_REG_DTTM TIMESTAMP NOT NULL,
	LAST_EDTR_ID VARCHAR(255) NOT NULL,
	LAST_CHNG_PROG_ID VARCHAR(255) NOT NULL,
	LAST_CHNG_DTTM TIMESTAMP,
	CONSTRAINT ACCOUNT_PKEY PRIMARY KEY (ID)
);



CREATE TABLE 'FAQ' (
  'ID' INT8 NOT NULL COMMENT 'FAQ일련번호',
  'FAQ_CLASS' varchar(2)  DEFAULT NULL COMMENT 'FAQ분류 (TENENT: 참여기관 PRICING: 과금정책 SYSTEM: 시스템장애 ETC:기타)',
  'FAQ_TITL' varchar(200)  DEFAULT NULL COMMENT 'FAQ제목',
  'FAQ_DSPL_RNG' varchar(3)  DEFAULT NULL COMMENT '노출범위코드\n: Issuer-Verifier-Holder 순\n111 : 전체노출\n100 : Issuer\n010 : Verifier\n001 : Holder\n110 : Issuer_Verifier\n101 : Issuer-Holder\n011 : Verifier-Holder',
  'FAQ_CTNT' varchar(2000)  DEFAULT NULL COMMENT 'FAQ내용',
  'FAQ_DSPL_STAT' varchar(2)  DEFAULT NULL COMMENT '노출상태코드(WRITING:작성중, PUBLISH:발행, EXPIRATIO:만료)',
  'FRST_RGSR_ID' varchar(100)  DEFAULT NULL COMMENT '최초등록자ID',
  'FRST_REG_PROG_ID' varchar(200)  DEFAULT NULL COMMENT '최초등록프로그램ID',
  'FRST_REG_DTTM' timestamp NULL DEFAULT NULL COMMENT '최초등록일시',
  'LAST_EDTR_ID' varchar(100)  DEFAULT NULL COMMENT '최종변경자ID',
  'LAST_CHNG_PROG_ID' varchar(200)  DEFAULT NULL COMMENT '최종변경프로그램ID',
  'LAST_CHNG_DTTM' timestamp NULL DEFAULT NULL COMMENT '최종변경일시',
	CONSTRAINT FAQ_PKEY PRIMARY KEY (ID)
);



CREATE TABLE 'NOTICE' (
  'ID' INT8 NOT NULL COMMENT '공지사항일련번호',
  'NOTC_DVCD' varchar(2)  NOT NULL COMMENT '공지사항구분코드(00: 중요공지, 01: 일반공지)',
  'NOTC_TITL' varchar(200)  NOT NULL COMMENT '공지사항제목',
  'NOTC_DSPL_RNG' varchar(3)  NOT NULL COMMENT '노출범위\n: Issuer-Verifier-Holder 순\n111 : 전체노출\n100 : Issuer\n010 : Verifier\n001 : Holder\n110 : Issuer_Verifier\n101 : Issuer-Holder\n011 : Verifier-Holder',
  'NOTC_CTNT' varchar(8000)  NOT NULL COMMENT '공지내용',
  'NOTC_DSPL_STAT' varchar(2)  DEFAULT NULL COMMENT '노출상태(WRITING:작성중, PUBLISH:발행, EXPIRATIO:만료)',
  'NOTC_STDT' varchar(8)  DEFAULT NULL COMMENT '공지사항시작일자',
  'NOTC_ENDT' varchar(8)  DEFAULT NULL COMMENT '공지사항종료일자',
  'FRST_RGSR_ID' varchar(100)  DEFAULT NULL COMMENT '최초등록자ID',
  'FRST_REG_PROG_ID' varchar(200)  DEFAULT NULL COMMENT '최초등록프로그램ID',
  'FRST_REG_DTTM' timestamp NULL DEFAULT NULL COMMENT '최초등록일시',
  'LAST_EDTR_ID' varchar(100)  DEFAULT NULL COMMENT '최종변경자ID',
  'LAST_CHNG_PROG_ID' varchar(200)  DEFAULT NULL COMMENT '최종변경프로그램ID',
  'LAST_CHNG_DTTM' timestamp NULL DEFAULT NULL COMMENT '최종변경일시',
CONSTRAINT NOTICE_PKEY PRIMARY KEY (ID)
); 



CREATE TABLE TENANT (
  ID INT8 NOT NULL COMMENT '참여기관일련번호',
  TENANT_ID VARCHAR(20) NOT NULL COMMENT '참여기관ID\N"ISS"/"VRF"/"HLD"+랜덤스트"',
	TENANT_DVID VARCHAR(1) NOT NULL COMMENT '참여기관구분코드\N(ISSUER, VERIFIER, ALL)',
	TENANT_NM VARCHAR(200) NOT NULL COMMENT '참여기관명',
	TENANT_DID VARCHAR(100) NOT NULL COMMENT '참여기관DID',
	TENANT_STAT VARCHAR(2) NOT NULL COMMENT '참여기관상태코드\N(00:정상, 01:정지, 02:해지)\N* 정지 : 라이선스 기한만료 상태',
	TENANT_ADMPG VARCHAR(1000) COMMENT '참여기관어드민페이지\N* 화면에서 입력받지 않고 규칙에 따라 생성해준다.\N"HTTPS://DNS_NAME:PORT/"+참여기관코드\NEX> HTTPS://DID.LAEL.COM:7090/BJ',
	LOGO_IMG_PATH VARCHAR(3000)  COMMENT '발급기관 목록에 보여지는 로고이미지 파일의 저장 경로',
	TENANT_HMPG VARCHAR(1000)  COMMENT '참여기관홈페이지',
	TENANT_ADDR VARCHAR(1000)  COMMENT '참여기관주소',
	OPEN_TRST_ORG_YN VARCHAR(1) NOT NULL COMMENT '공개신뢰기관여부(Y/N)',
	FRST_RGSR_ID VARCHAR(100) NOT NULL COMMENT '최초등록자ID',
	FRST_REG_PROG_ID VARCHAR(200) NOT NULL COMMENT '최초등록프로그램ID',
	FRST_REG_DTTM TIMESTAMP  not NULL COMMENT '최초등록일시',
	LAST_EDTR_ID VARCHAR(100)  COMMENT '최종변경자ID',
	LAST_CHNG_PROG_ID VARCHAR(200) COMMENT '최종변경프로그램ID',
	LAST_CHNG_DTTM TIMESTAMP  COMMENT '최종변경일시',
CONSTRAINT TENENT_PKEY PRIMARY KEY (ID)
); 


DROP TABLE TENANT;

CREATE TABLE TENANT (
  ID INT8 NOT NULL,
  TENANT_ID VARCHAR(20) NOT NULL ,
	TENANT_TYPE VARCHAR(10) NOT NULL,
	TENANT_NAME VARCHAR(200) NOT NULL ,
	TENANT_DID VARCHAR(100),
	TENANT_STATUS VARCHAR(10) NOT NULL ,
	TENANT_HOME_URL VARCHAR(1000) ,
	TENANT_INVITATION_URL VARCHAR(1000) ,
	TENANT_LOGO_PATH VARCHAR(3000)  ,
	TENANT_ADDR VARCHAR(1000) ,
	TRUST_TENANT BOOLEAN NOT NULL ,
	FRST_RGSR_ID VARCHAR(100) NOT NULL ,
	FRST_REG_PROG_ID VARCHAR(200) NOT NULL ,
	FRST_REG_DTTM TIMESTAMP  not NULL ,
	LAST_EDTR_ID VARCHAR(100)  ,
	LAST_CHNG_PROG_ID VARCHAR(200) ,
	LAST_CHNG_DTTM TIMESTAMP  ,
CONSTRAINT TENENT_PKEY PRIMARY KEY (ID)
); 

INSERT INTO public.tenant (id, tenant_id, tenant_type, tenant_name, tenant_did, tenant_status, tenant_home_url, tenant_invitation_url, tenant_logo_path, tenant_addr, trust_tenant, frst_rgsr_id, frst_reg_prog_id, frst_reg_dttm, last_edtr_id, last_chng_prog_id, last_chng_dttm) 
values
(1, 'ISStjalskdjxc', 'ISSUER', 'LG CNS', 'RTHAnR3aKM5iSNmHnr4am4', 'ACTIVATE', NULL, 'https://devacapyinbound.duckdns.org?c_i=eyJAdHlwZSI6ICJkaWQ6c292OkJ6Q2JzTlloTXJqSGlxWkRUVUFTSGc7c3BlYy9jb25uZWN0aW9ucy8xLjAvaW52aXRhdGlvbiIsICJAaWQiOiAiZDU1ZGFiOTYtNjk4Yi00M2U0LWI3ZmItNTUzMTg1ZjcwOGZmIiwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwczovL2RldmFjYXB5aW5ib3VuZC5kdWNrZG5zLm9yZyIsICJpbWFnZVVybCI6ICJodHRwczovL3JvYm9oYXNoLm9yZy9MR0NOUyIsICJsYWJlbCI6ICJMR0NOUyIsICJyZWNpcGllbnRLZXlzIjogWyJGc0VEbjRlZmdLTnBlRXFRWXlpZmNLRlM3NkxTWHVXbkhuWjR1ZGRLeVRvdiJdfQ==', NULL, NULL, True, 'test', 'test', '2022-01-01 11:11:11.000', 'test', 'test', '2022-01-01 11:11:11.000');


comment on column TENANT.ID is '참여기관일련번호';




CREATE TABLE SCHEMA (
                SCHEMA_ID VARCHAR(200) NOT NULL,
                CREDENTIAL_DEFINITION_ID VARCHAR(200),
                SCHEMA_TYCD VARCHAR(20) NOT NULL,
                SCHEMA_VER VARCHAR(5) NOT NULL,
                SCHEMA_NM VARCHAR(100) NOT NULL,
                SCHEMA_STCD VARCHAR(20) NOT NULL,
                TAGGING_YN VARCHAR(1) NOT NULL,
                FRST_RGSR_ID VARCHAR(100) NOT NULL,
                FRST_REG_PROG_ID VARCHAR(200) NOT NULL,
                FRST_REG_DTTM TIMESTAMP NOT NULL,
                LAST_EDTR_ID VARCHAR(100) NOT NULL,
                LAST_CHNG_PROG_ID VARCHAR(200) NOT NULL,
                LAST_CHNG_DTTM TIMESTAMP NOT NULL,
                CONSTRAINT schema_pk PRIMARY KEY (SCHEMA_ID)
);
COMMENT ON TABLE DID_SOLUTION.SCHEMA IS '스키마';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA.SCHEMA_ID IS '스키마ID';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA.CREDENTIAL_DEFINITION_ID IS 'CredentialDefinitionId';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA.SCHEMA_TYCD IS '스키마유형코드
(EMPLOYEEID)';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA.SCHEMA_VER IS '스키마버전';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA.SCHEMA_NM IS '스키마명';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA.SCHEMA_STCD IS '스키마상태코드
(AVAILABLE, SUSPEND)';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA.TAGGING_YN IS '태깅여부';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA.FRST_RGSR_ID IS '최초등록자ID';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA.FRST_REG_PROG_ID IS '최초등록프로그램ID';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA.FRST_REG_DTTM IS '최초등록일시';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA.LAST_EDTR_ID IS '최종변경자ID';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA.LAST_CHNG_PROG_ID IS '최종변경프로그램ID';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA.LAST_CHNG_DTTM IS '최종변경일시';
 
 
CREATE TABLE DID_SOLUTION.SCHEMA_ATTRIBUTE (
                SCHEMA_ID VARCHAR(200) NOT NULL,
                ATTRIBUTE_CODE VARCHAR(100) NOT NULL,
                ATTRIBUTE_NAME VARCHAR(100) NOT NULL,
                MIME_TYPE VARCHAR(100) NOT NULL,
                FRST_RGSR_ID VARCHAR(100) NOT NULL,
                FRST_REG_PROG_ID VARCHAR(200) NOT NULL,
                FRST_REG_DTTM TIMESTAMP NOT NULL,
                LAST_EDTR_ID VARCHAR(100) NOT NULL,
                LAST_CHNG_PROG_ID VARCHAR(200) NOT NULL,
                LAST_CHNG_DTTM TIMESTAMP NOT NULL,
                CONSTRAINT schema_attribute_pk PRIMARY KEY (SCHEMA_ID, ATTRIBUTE_CODE)
);
COMMENT ON TABLE DID_SOLUTION.SCHEMA_ATTRIBUTE IS '스키마속성';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA_ATTRIBUTE.SCHEMA_ID IS '스키마ID';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA_ATTRIBUTE.ATTRIBUTE_CODE IS '속성코드';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA_ATTRIBUTE.ATTRIBUTE_NAME IS '속성명';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA_ATTRIBUTE.MIME_TYPE IS '마임타입';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA_ATTRIBUTE.FRST_RGSR_ID IS '최초등록자ID';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA_ATTRIBUTE.FRST_REG_PROG_ID IS '최초등록프로그램ID';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA_ATTRIBUTE.FRST_REG_DTTM IS '최초등록일시';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA_ATTRIBUTE.LAST_EDTR_ID IS '최종변경자ID';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA_ATTRIBUTE.LAST_CHNG_PROG_ID IS '최종변경프로그램ID';
COMMENT ON COLUMN DID_SOLUTION.SCHEMA_ATTRIBUTE.LAST_CHNG_DTTM IS '최종변경일시';
 
 
CREATE TABLE DID_SOLUTION.ISSUE_RULE (
                ISSUE_RULE_ID VARCHAR(200) NOT NULL,
                ISSUE_RULE_NAME VARCHAR(200) NOT NULL,
                CREDENTIAL_DEFINITION_ID VARCHAR(200) NOT NULL,
                SCHEMA_ID VARCHAR(200) NOT NULL,
                ISSUE_STCD VARCHAR(10),
                REVOCATION_REGISTRY_SIZE INTEGER DEFAULT 0 NOT NULL,
                DESCRIPTION VARCHAR(200),
                INQR_IDF_NM1 VARCHAR(100),
                INQR_IDF_NM2 VARCHAR(100),
                INQR_IDF_NM3 VARCHAR(100),
                INQR_IDF_NM4 VARCHAR(100),
                INQR_IDF_NM5 VARCHAR(100),
                USER_AUTH_PAGE_URL VARCHAR(500) NOT NULL,
                API_METHOD VARCHAR(10),
                USER_INFO_REQ_URL VARCHAR(500) NOT NULL,
                ATTR_MAPPING VARCHAR(3000),
                EXP_DT_SET_YN VARCHAR(1) NOT NULL,
                VALIDITY_DAYS INTEGER,
                DEL_INF_YN VARCHAR(1) NOT NULL,
                DEL_INF_URL VARCHAR(1000),
                SCHEMA_TYCD VARCHAR(20) NOT NULL,
                BACKGROUND_IMG BYTEA,
                LOGO_IMG BYTEA,
                TEMP_ITEM_MAPPING VARCHAR(3000) NOT NULL,
                FRST_RGSR_ID VARCHAR(100) NOT NULL,
                FRST_REG_PROG_ID VARCHAR(200) NOT NULL,
                FRST_REG_DTTM TIMESTAMP NOT NULL,
                LAST_EDTR_ID VARCHAR(100) NOT NULL,
                LAST_CHNG_PROG_ID VARCHAR(200) NOT NULL,
                LAST_CHNG_DTTM TIMESTAMP NOT NULL,
                CONSTRAINT issue_rule_pk PRIMARY KEY (ISSUE_RULE_ID)
);
COMMENT ON TABLE DID_SOLUTION.ISSUE_RULE IS '발급룰';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.ISSUE_RULE_ID IS '발급룰ID';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.ISSUE_RULE_NAME IS '발급룰명(사용자화면노출)';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.CREDENTIAL_DEFINITION_ID IS 'CredentialDefinitionId';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.ISSUE_STCD IS '발급상태코드
(SETTINGUP, AVAILABLE, PAUSE)';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.REVOCATION_REGISTRY_SIZE IS '발급규모';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.DESCRIPTION IS '증명서설명';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.INQR_IDF_NM1 IS '조회식별자명1';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.INQR_IDF_NM2 IS '조회식별자명2';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.INQR_IDF_NM3 IS '조회식별자명3';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.INQR_IDF_NM4 IS '조회식별자명4';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.INQR_IDF_NM5 IS '조회식별자명5';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.USER_AUTH_PAGE_URL IS '사용자인증페이지URL';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.API_METHOD IS 'API메소드(GET,POST)';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.USER_INFO_REQ_URL IS '사용자정보요청URL';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.ATTR_MAPPING IS '속성매핑
속성-응답데이터 연결정보
;를 구분자로 속성과 응답데이터를 번갈아가며 기술.
예)cla.compname:CompanyNm;cla.empname:EmpNm;cla.empno:EmpNo';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.EXP_DT_SET_YN IS '유효기간설정여부';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.VALIDITY_DAYS IS '유효기간일수';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.DEL_INF_YN IS '삭제통지여부';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.DEL_INF_URL IS '삭제통지URL';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.SCHEMA_TYCD IS '스키마유형코드
(EMPLOYEEID)';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.BACKGROUND_IMG IS '배경이미지';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.LOGO_IMG IS '로고이미지';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.TEMP_ITEM_MAPPING IS '속성매핑
변수항목-크리덴셜속성 연결정보
;를 구분자로 변수항목과 속성을 번갈아가며 기술.
예)3;cla.compname;CompanyNm;cla.empname;EmpNm;cla.empno;EmpNo';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.FRST_RGSR_ID IS '최초등록자ID';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.FRST_REG_PROG_ID IS '최초등록프로그램ID';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.FRST_REG_DTTM IS '최초등록일시';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.LAST_EDTR_ID IS '최종변경자ID';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.LAST_CHNG_PROG_ID IS '최종변경프로그램ID';
COMMENT ON COLUMN DID_SOLUTION.ISSUE_RULE.LAST_CHNG_DTTM IS '최종변경일시';