-- DROP SCHEMA did_solution;

CREATE SCHEMA did_solution AUTHORIZATION solution;

COMMENT ON SCHEMA did_solution IS 'DID SOLUTION';


-- did_solution.account definition

-- Drop table

-- DROP TABLE did_solution.account;

CREATE TABLE did_solution.account (
                                      id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 계정일련번호
                                      account_id varchar(255) NOT NULL, -- 계정ID
                                      pswd_hash_val varchar(255) NULL, -- 비밀번호 HASH
                                      pswd_falr_tmcnt int4 NOT NULL, -- 비밀번호 실패 횟수
                                      flnm varchar(255) NOT NULL, -- 이름
                                      cpno varchar(31) NULL, -- 휴대전화번호
                                      email varchar(255) NULL, -- 이메일
                                      account_status varchar(15) NOT NULL, -- 계정상태
                                      account_type varchar(15) NULL, -- 계정종류 (ADMIN/GENERAL)
                                      auth_ip varchar(255) NULL, -- 접속가능IP
                                      last_login_dttm timestamp NULL, -- 최종 접속일
                                      last_pswd_chng_dttm timestamp NULL, -- 패스워드변경일
                                      login_sesn_id varchar(255) NULL, -- 로그인세션ID
                                      frst_rgsr_id varchar(255) NOT NULL, -- 최초등록자ID
                                      frst_reg_prog_id varchar(255) NOT NULL, -- 최초등록프로그램ID
                                      frst_reg_dttm timestamp NOT NULL, -- 최초등록일시
                                      last_edtr_id varchar(255) NOT NULL, -- 최종변경자ID
                                      last_chng_prog_id varchar(255) NOT NULL, -- 최종변경프로그램ID
                                      last_chng_dttm timestamp NULL, -- 최종변경일시
                                      telno varchar(255) NULL, -- 유선전화번호
                                      CONSTRAINT account_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE did_solution.account IS 'Admin 관리자 계정';

-- Column comments

COMMENT ON COLUMN did_solution.account.id IS '계정일련번호';
COMMENT ON COLUMN did_solution.account.account_id IS '계정ID';
COMMENT ON COLUMN did_solution.account.pswd_hash_val IS '비밀번호 HASH';
COMMENT ON COLUMN did_solution.account.pswd_falr_tmcnt IS '비밀번호 실패 횟수';
COMMENT ON COLUMN did_solution.account.flnm IS '이름';
COMMENT ON COLUMN did_solution.account.cpno IS '휴대전화번호';
COMMENT ON COLUMN did_solution.account.email IS '이메일';
COMMENT ON COLUMN did_solution.account.account_status IS '계정상태';
COMMENT ON COLUMN did_solution.account.account_type IS '계정종류 (ADMIN/GENERAL)';
COMMENT ON COLUMN did_solution.account.auth_ip IS '접속가능IP';
COMMENT ON COLUMN did_solution.account.last_login_dttm IS '최종 접속일';
COMMENT ON COLUMN did_solution.account.last_pswd_chng_dttm IS '패스워드변경일';
COMMENT ON COLUMN did_solution.account.login_sesn_id IS '로그인세션ID';
COMMENT ON COLUMN did_solution.account.frst_rgsr_id IS '최초등록자ID';
COMMENT ON COLUMN did_solution.account.frst_reg_prog_id IS '최초등록프로그램ID';
COMMENT ON COLUMN did_solution.account.frst_reg_dttm IS '최초등록일시';
COMMENT ON COLUMN did_solution.account.last_edtr_id IS '최종변경자ID';
COMMENT ON COLUMN did_solution.account.last_chng_prog_id IS '최종변경프로그램ID';
COMMENT ON COLUMN did_solution.account.last_chng_dttm IS '최종변경일시';
COMMENT ON COLUMN did_solution.account.telno IS '유선전화번호';


-- did_solution.faq definition

-- Drop table

-- DROP TABLE did_solution.faq;

CREATE TABLE did_solution.faq (
                                  id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- FAQ 일련번호
                                  faq_class varchar(16) NOT NULL, -- FAQ분류 (TENENT: 참여기관 PRICING: 과금정책 SYSTEM: 시스템장애 ETC:기타)
                                  faq_title varchar(256) NOT NULL, -- FAQ제목
                                  faq_display_range varchar(10) NOT NULL, -- 노출범위: I,V,H
                                  faq_content varchar(2048) NOT NULL, -- FAQ내용
                                  faq_status varchar(16) NOT NULL DEFAULT 'WRITING'::character varying, -- 노출상태(WRITING:작성중, PUBLISH:발행, EXPIRATIO:만료)
                                  frst_rgsr_id varchar(100) NOT NULL, -- 최초등록자ID
                                  frst_reg_prog_id varchar(200) NOT NULL, -- 최초등록프로그램ID
                                  frst_reg_dttm timestamp NOT NULL, -- 최초등록일시
                                  last_edtr_id varchar(100) NULL, -- 최종변경자ID
                                  last_chng_prog_id varchar(200) NULL, -- 최종변경프로그램ID
                                  last_chng_dttm timestamp NULL, -- 최종변경일시
                                  CONSTRAINT faq_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE did_solution.faq IS 'FAQ';

-- Column comments

COMMENT ON COLUMN did_solution.faq.id IS 'FAQ 일련번호';
COMMENT ON COLUMN did_solution.faq.faq_class IS 'FAQ분류 (TENENT: 참여기관 PRICING: 과금정책 SYSTEM: 시스템장애 ETC:기타)';
COMMENT ON COLUMN did_solution.faq.faq_title IS 'FAQ제목';
COMMENT ON COLUMN did_solution.faq.faq_display_range IS '노출범위: I,V,H';
COMMENT ON COLUMN did_solution.faq.faq_content IS 'FAQ내용';
COMMENT ON COLUMN did_solution.faq.faq_status IS '노출상태(WRITING:작성중, PUBLISH:발행, EXPIRATIO:만료)';
COMMENT ON COLUMN did_solution.faq.frst_rgsr_id IS '최초등록자ID';
COMMENT ON COLUMN did_solution.faq.frst_reg_prog_id IS '최초등록프로그램ID';
COMMENT ON COLUMN did_solution.faq.frst_reg_dttm IS '최초등록일시';
COMMENT ON COLUMN did_solution.faq.last_edtr_id IS '최종변경자ID';
COMMENT ON COLUMN did_solution.faq.last_chng_prog_id IS '최종변경프로그램ID';
COMMENT ON COLUMN did_solution.faq.last_chng_dttm IS '최종변경일시';


-- did_solution."notice" definition

-- Drop table

-- DROP TABLE did_solution."notice";

CREATE TABLE did_solution."notice" (
                                       id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 공지사항 일련번호
                                       notice_level varchar(15) NOT NULL, -- 공지사항구분코드(CRITICAL: 중요공지, GENERAL: 일반공지)
                                       notice_title varchar(200) NOT NULL, -- 공지사항제목
                                       notice_range varchar(15) NOT NULL, -- 노출상태(WRITING:작성중, PUBLISH:발행, EXPIRATION:만료)
                                       notice_content varchar(8000) NOT NULL, -- 공지내용
                                       notice_status varchar(15) NULL DEFAULT NULL::character varying,
                                       notice_start_date timestamp NULL, -- 공지사항시작일자
                                       notice_end_date timestamp NULL, -- 공지사항종료일자
                                       frst_rgsr_id varchar(100) NULL DEFAULT NULL::character varying, -- 최초등록자ID
                                       frst_reg_prog_id varchar(200) NULL DEFAULT NULL::character varying, -- 최초등록프로그램ID
                                       frst_reg_dttm timestamp NULL, -- 최초등록일시
                                       last_edtr_id varchar(100) NULL DEFAULT NULL::character varying, -- 최종변경자ID
                                       last_chng_prog_id varchar(200) NULL DEFAULT NULL::character varying, -- 최종변경프로그램ID
                                       last_chng_dttm timestamp NULL, -- 최종변경일시
                                       CONSTRAINT notice_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE did_solution."notice" IS '공지사항';

-- Column comments

COMMENT ON COLUMN did_solution."notice".id IS '공지사항 일련번호';
COMMENT ON COLUMN did_solution."notice".notice_level IS '공지사항구분코드(CRITICAL: 중요공지, GENERAL: 일반공지)';
COMMENT ON COLUMN did_solution."notice".notice_title IS '공지사항제목';
COMMENT ON COLUMN did_solution."notice".notice_range IS '노출상태(WRITING:작성중, PUBLISH:발행, EXPIRATION:만료)';
COMMENT ON COLUMN did_solution."notice".notice_content IS '공지내용';
COMMENT ON COLUMN did_solution."notice".notice_start_date IS '공지사항시작일자';
COMMENT ON COLUMN did_solution."notice".notice_end_date IS '공지사항종료일자';
COMMENT ON COLUMN did_solution."notice".frst_rgsr_id IS '최초등록자ID';
COMMENT ON COLUMN did_solution."notice".frst_reg_prog_id IS '최초등록프로그램ID';
COMMENT ON COLUMN did_solution."notice".frst_reg_dttm IS '최초등록일시';
COMMENT ON COLUMN did_solution."notice".last_edtr_id IS '최종변경자ID';
COMMENT ON COLUMN did_solution."notice".last_chng_prog_id IS '최종변경프로그램ID';
COMMENT ON COLUMN did_solution."notice".last_chng_dttm IS '최종변경일시';


-- did_solution."schema" definition

-- Drop table

-- DROP TABLE did_solution."schema";

CREATE TABLE did_solution."schema" (
                                       id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                       schema_id varchar(200) NOT NULL, -- 스키마ID
                                       schema_name varchar(100) NOT NULL, -- 스키마명
                                       frst_rgsr_id varchar(100) NOT NULL, -- 최초등록자ID
                                       frst_reg_prog_id varchar(200) NOT NULL, -- 최초등록프로그램ID
                                       frst_reg_dttm timestamp NOT NULL, -- 최초등록일시
                                       last_edtr_id varchar(100) NOT NULL, -- 최종변경자ID
                                       last_chng_prog_id varchar(200) NOT NULL, -- 최종변경프로그램ID
                                       last_chng_dttm timestamp NOT NULL, -- 최종변경일시
                                       CONSTRAINT schema_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE did_solution."schema" IS '스키마';

-- Column comments

COMMENT ON COLUMN did_solution."schema".schema_id IS '스키마ID';
COMMENT ON COLUMN did_solution."schema".schema_name IS '스키마명';
COMMENT ON COLUMN did_solution."schema".frst_rgsr_id IS '최초등록자ID';
COMMENT ON COLUMN did_solution."schema".frst_reg_prog_id IS '최초등록프로그램ID';
COMMENT ON COLUMN did_solution."schema".frst_reg_dttm IS '최초등록일시';
COMMENT ON COLUMN did_solution."schema".last_edtr_id IS '최종변경자ID';
COMMENT ON COLUMN did_solution."schema".last_chng_prog_id IS '최종변경프로그램ID';
COMMENT ON COLUMN did_solution."schema".last_chng_dttm IS '최종변경일시';


-- did_solution.tenant definition

-- Drop table

-- DROP TABLE did_solution.tenant;

CREATE TABLE did_solution.tenant (
                                     id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                     frst_reg_prog_id varchar(255) NOT NULL, -- 최초등록프로그램ID
                                     frst_rgsr_id varchar(255) NOT NULL, -- 최초등록자ID
                                     frst_reg_dttm timestamp NOT NULL, -- 최초등록일시
                                     last_chng_prog_id varchar(255) NOT NULL, -- 최종변경프로그램ID
                                     last_chng_dttm timestamp NULL, -- 최종변경일시
                                     last_edtr_id varchar(255) NOT NULL, -- 최종변경자ID
                                     tenant_addr varchar(500) NULL, -- 참여기관주소
                                     tenant_did varchar(255) NULL, -- 참여기관DID
                                     tenant_home_url varchar(500) NULL, -- 참여기관홈페이지
                                     tenant_id varchar(255) NOT NULL, -- 참여기관일련번호
                                     tenant_invitation_url varchar(2000) NULL, -- 참여기관 Invitation url
                                     tenant_name varchar(255) NOT NULL, -- 참여기관명
                                     tenant_status varchar(255) NOT NULL, -- 참여기관상태
                                     tenant_type varchar(255) NOT NULL, -- 참여기관 종류 (ISSUER/VERIFIER/ALL)
                                     trust_tenant bool NULL, -- 공개신뢰기관여부
                                     tenant_logo oid NULL, -- 발급기관 목록에 보여지는 로고이미지 파일의 저장 경로
                                     tenant_logo_filename varchar(255) NULL, -- 발급기관 목록에 보여지는 로고이미지 파일명
                                     tenant_wallet_id varchar(255) NULL, -- 테넌트 agent wallet id
                                     CONSTRAINT tenant_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE did_solution.tenant IS '참여기관';

-- Column comments

COMMENT ON COLUMN did_solution.tenant.frst_reg_prog_id IS '최초등록프로그램ID';
COMMENT ON COLUMN did_solution.tenant.frst_rgsr_id IS '최초등록자ID';
COMMENT ON COLUMN did_solution.tenant.frst_reg_dttm IS '최초등록일시';
COMMENT ON COLUMN did_solution.tenant.last_chng_prog_id IS '최종변경프로그램ID';
COMMENT ON COLUMN did_solution.tenant.last_chng_dttm IS '최종변경일시';
COMMENT ON COLUMN did_solution.tenant.last_edtr_id IS '최종변경자ID';
COMMENT ON COLUMN did_solution.tenant.tenant_addr IS '참여기관주소';
COMMENT ON COLUMN did_solution.tenant.tenant_did IS '참여기관DID';
COMMENT ON COLUMN did_solution.tenant.tenant_home_url IS '참여기관홈페이지';
COMMENT ON COLUMN did_solution.tenant.tenant_id IS '참여기관일련번호';
COMMENT ON COLUMN did_solution.tenant.tenant_invitation_url IS '참여기관 Invitation url';
COMMENT ON COLUMN did_solution.tenant.tenant_name IS '참여기관명';
COMMENT ON COLUMN did_solution.tenant.tenant_status IS '참여기관상태';
COMMENT ON COLUMN did_solution.tenant.tenant_type IS '참여기관 종류 (ISSUER/VERIFIER/ALL)';
COMMENT ON COLUMN did_solution.tenant.trust_tenant IS '공개신뢰기관여부';
COMMENT ON COLUMN did_solution.tenant.tenant_logo IS '발급기관 목록에 보여지는 로고이미지 파일의 저장 경로';
COMMENT ON COLUMN did_solution.tenant.tenant_logo_filename IS '발급기관 목록에 보여지는 로고이미지 파일명';
COMMENT ON COLUMN did_solution.tenant.tenant_wallet_id IS '테넌트 agent wallet id';


-- did_solution.term definition

-- Drop table

-- DROP TABLE did_solution.term;

CREATE TABLE did_solution.term (
                                   id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 약관 일련번호
                                   term_content varchar(8000) NOT NULL, -- 약관내용
                                   frst_rgsr_id varchar(100) NOT NULL, -- 최초등록자ID
                                   frst_reg_prog_id varchar(200) NOT NULL, -- 최초등록프로그램ID
                                   frst_reg_dttm timestamp NOT NULL, -- 최초등록일시
                                   last_edtr_id varchar(100) NULL, -- 최종변경자ID
                                   last_chng_prog_id varchar(200) NULL, -- 최종변경프로그램ID
                                   last_chng_dttm timestamp NULL, -- 최종변경일시
                                   CONSTRAINT term_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE did_solution.term IS '약관';

-- Column comments

COMMENT ON COLUMN did_solution.term.id IS '약관 일련번호';
COMMENT ON COLUMN did_solution.term.term_content IS '약관내용';
COMMENT ON COLUMN did_solution.term.frst_rgsr_id IS '최초등록자ID';
COMMENT ON COLUMN did_solution.term.frst_reg_prog_id IS '최초등록프로그램ID';
COMMENT ON COLUMN did_solution.term.frst_reg_dttm IS '최초등록일시';
COMMENT ON COLUMN did_solution.term.last_edtr_id IS '최종변경자ID';
COMMENT ON COLUMN did_solution.term.last_chng_prog_id IS '최종변경프로그램ID';
COMMENT ON COLUMN did_solution.term.last_chng_dttm IS '최종변경일시';


-- did_solution.credential definition

-- Drop table

-- DROP TABLE did_solution.credential;

CREATE TABLE did_solution.credential (
                                         id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 증명서 일련번호
                                         credential_id varchar(200) NOT NULL, -- 증명서 ID
                                         schema_id int8 NOT NULL,
                                         credential_name varchar(200) NOT NULL, -- 증명서명(사용자화면노출)
                                         credential_definition_id varchar(200) NOT NULL, -- CredentialDefinitionId
                                         trust_credential_yn bool NOT NULL, -- trust 인증서 여부
                                         credential_type varchar(20) NOT NULL, -- 스키마유형(EMPLOYEEID)
                                         description varchar(200) NULL, -- 증명서설명
                                         user_auth_page_url varchar(500) NOT NULL, -- 사용자인증페이지URL
                                         exp_dt_set_yn bool NOT NULL, -- 유효기간설정여부
                                         validity_days int4 NULL DEFAULT 0, -- 유효기간일수
                                         template_item_mapping varchar(3000) NOT NULL, -- 속성매핑 변수항목-크리덴셜속성 연결정보 ;를 구분자로 변수항목과 속성을 번갈아가며 기술. 예)3;cla.compname;CompanyNm;cla.empname;EmpNm;cla.empno;EmpNo
                                         frst_rgsr_id varchar(100) NOT NULL, -- 최초등록자ID
                                         frst_reg_prog_id varchar(200) NOT NULL, -- 최초등록프로그램ID
                                         frst_reg_dttm timestamp NOT NULL, -- 최초등록일시
                                         last_edtr_id varchar(100) NOT NULL, -- 최종변경자ID
                                         last_chng_prog_id varchar(200) NOT NULL, -- 최종변경프로그램ID
                                         last_chng_dttm timestamp NOT NULL, -- 최종변경일시
                                         tenant_id int8 NOT NULL,
                                         background_img oid NULL,
                                         logo_img oid NULL,
                                         background_img_filename varchar(200) NULL,
                                         logo_img_filename varchar(200) NULL,
                                         service_extension_info varchar(5000) NULL, -- 크리덴셜을 이용한 서비스에서 사용되는 확장 정보   (Json string 형태 ) nfcAppId : 7
                                         CONSTRAINT credential_pkey PRIMARY KEY (id),
                                         CONSTRAINT credential_schema_id_fk FOREIGN KEY (schema_id) REFERENCES did_solution."schema"(id),
                                         CONSTRAINT credential_tenant_id_fk FOREIGN KEY (tenant_id) REFERENCES did_solution.tenant(id)
);
CREATE INDEX credential_credential_id_index ON did_solution.credential USING btree (credential_id);
COMMENT ON TABLE did_solution.credential IS '증명서';

-- Column comments

COMMENT ON COLUMN did_solution.credential.id IS '증명서 일련번호';
COMMENT ON COLUMN did_solution.credential.credential_id IS '증명서 ID';
COMMENT ON COLUMN did_solution.credential.credential_name IS '증명서명(사용자화면노출)';
COMMENT ON COLUMN did_solution.credential.credential_definition_id IS 'CredentialDefinitionId';
COMMENT ON COLUMN did_solution.credential.trust_credential_yn IS 'trust 인증서 여부';
COMMENT ON COLUMN did_solution.credential.credential_type IS '스키마유형(EMPLOYEEID)';
COMMENT ON COLUMN did_solution.credential.description IS '증명서설명';
COMMENT ON COLUMN did_solution.credential.user_auth_page_url IS '사용자인증페이지URL';
COMMENT ON COLUMN did_solution.credential.exp_dt_set_yn IS '유효기간설정여부';
COMMENT ON COLUMN did_solution.credential.validity_days IS '유효기간일수';
COMMENT ON COLUMN did_solution.credential.template_item_mapping IS '속성매핑 변수항목-크리덴셜속성 연결정보 ;를 구분자로 변수항목과 속성을 번갈아가며 기술. 예)3;cla.compname;CompanyNm;cla.empname;EmpNm;cla.empno;EmpNo';
COMMENT ON COLUMN did_solution.credential.frst_rgsr_id IS '최초등록자ID';
COMMENT ON COLUMN did_solution.credential.frst_reg_prog_id IS '최초등록프로그램ID';
COMMENT ON COLUMN did_solution.credential.frst_reg_dttm IS '최초등록일시';
COMMENT ON COLUMN did_solution.credential.last_edtr_id IS '최종변경자ID';
COMMENT ON COLUMN did_solution.credential.last_chng_prog_id IS '최종변경프로그램ID';
COMMENT ON COLUMN did_solution.credential.last_chng_dttm IS '최종변경일시';
COMMENT ON COLUMN did_solution.credential.service_extension_info IS '크리덴셜을 이용한 서비스에서 사용되는 확장 정보   (Json string 형태 ) nfcAppId : 7';


-- did_solution.schema_attribute definition

-- Drop table

-- DROP TABLE did_solution.schema_attribute;

CREATE TABLE did_solution.schema_attribute (
                                               id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                               schema_id int8 NOT NULL, -- 스키마ID
                                               attribute_code varchar(100) NOT NULL, -- 속성코드
                                               attribute_name varchar(100) NOT NULL, -- 속성명
                                               mime_type varchar(100) NOT NULL, -- 마임타입
                                               frst_rgsr_id varchar(100) NOT NULL, -- 최초등록자ID
                                               frst_reg_prog_id varchar(200) NOT NULL, -- 최초등록프로그램ID
                                               frst_reg_dttm timestamp NOT NULL, -- 최초등록일시
                                               last_edtr_id varchar(100) NOT NULL, -- 최종변경자ID
                                               last_chng_prog_id varchar(200) NOT NULL, -- 최종변경프로그램ID
                                               last_chng_dttm timestamp NOT NULL, -- 최종변경일시
                                               CONSTRAINT schema_attribute_pkey PRIMARY KEY (id),
                                               CONSTRAINT schema_attribute_schema_id_fk FOREIGN KEY (schema_id) REFERENCES did_solution."schema"(id)
);
COMMENT ON TABLE did_solution.schema_attribute IS '스키마속성';

-- Column comments

COMMENT ON COLUMN did_solution.schema_attribute.schema_id IS '스키마ID';
COMMENT ON COLUMN did_solution.schema_attribute.attribute_code IS '속성코드';
COMMENT ON COLUMN did_solution.schema_attribute.attribute_name IS '속성명';
COMMENT ON COLUMN did_solution.schema_attribute.mime_type IS '마임타입';
COMMENT ON COLUMN did_solution.schema_attribute.frst_rgsr_id IS '최초등록자ID';
COMMENT ON COLUMN did_solution.schema_attribute.frst_reg_prog_id IS '최초등록프로그램ID';
COMMENT ON COLUMN did_solution.schema_attribute.frst_reg_dttm IS '최초등록일시';
COMMENT ON COLUMN did_solution.schema_attribute.last_edtr_id IS '최종변경자ID';
COMMENT ON COLUMN did_solution.schema_attribute.last_chng_prog_id IS '최종변경프로그램ID';
COMMENT ON COLUMN did_solution.schema_attribute.last_chng_dttm IS '최종변경일시';




