apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-master-env
data:
  MASTER: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-master-config
data:
  redis-conf: |
    bind 0.0.0.0 
    maxmemory 2mb
    maxmemory-policy allkeys-lru
    appendonly no
    save ""