apiVersion: v1
kind: Pod
metadata:
  name: redis-master
  labels:
    app: redis-master
spec:
  containers:
  - name: redis
    image: redis:7.0.2-bullseye
    command:
      - redis-server
      - /etc/redis/redis.conf
    envFrom:
      - configMapRef:
          name: redis-master-env
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: 0.5
    volumeMounts:
    - mountPath: /etc/redis
      name: config
  volumes:
    - name: config
      configMap:
        name: redis-master-config
        items:
        - key: redis-conf
          path: redis.conf