apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: ingress-solution-backend
  namespace: common-system
spec:
  rules:
    - host: _DOMAIN_
      http:
        paths:
          - path: /api/*
            backend:
              serviceName: solution-backend
              servicePort: 80
